### ISSUE TITLE
line 193: ${OPTARG^^}: bad substitution

### ISSUE THREAD

**Issue by gr2m** [paulbarton90/gh-clean-notifications#6]
I tried to clean out notifications for closed items but got this error

```
gh extension install paulbarton90/gh-clean-notifications
gh clean-notifications -s merged,closed
/Users/gr2m/.local/share/gh/extensions/gh-clean-notifications/gh-clean-notifications: line 193: ${OPTARG^^}: bad substitution
```

I don't know go much, let me know how I can help to debug the problem

**Comment by paulbarton90** [comment]
The default is also `merged,closed` so you could run `gh clean-notifications` on it's own without specifying that to get the same result. You may run into the issue that is being fixed in https://github.com/paulbarton90/gh-clean-notifications/pull/7 though depending on how many notifications it has to clean up.

I think to figure out where the issue is coming from, I would need to know the version of bash that you are running. This can be found via `/usr/bin/env bash --version`. For reference this is what I am using and testing with:

```shell
$ /usr/bin/env bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by gr2m** [comment]
her is some info

```
$ /usr/bin/env bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.

$ gh --version
gh version 2.47.0 (2024-04-03)
https://github.com/cli/cli/releases/tag/v2.47.0

$ gh auth status
github.com
  ✓ Logged in to github.com account gr2m (GITHUB_TOKEN)
  - Active account: true
  - Git operations protocol: https
  - Token: ghp_************************************
  - Token scopes: 'notifications', 'project', 'repo', 'workflow', 'write:org'

  ✓ Logged in to github.com account gr2m (keyring)
  - Active account: false
  - Git operations protocol: https
  - Token: gho_************************************
  - Token scopes: 'gist', 'read:org', 'repo', 'workflow'
```

And here is what I get if I run without the `-s merged,closed` flag

```
$ gh clean-notifications
gh: Field 'notificationThreads' doesn't exist on type 'User'
Variable $first is declared by NotificationsQuery but not used
Variable $endCursor is declared by NotificationsQuery but not used
Variable $miscQuery is declared by NotificationsQuery but not used
```



> it's most likely because the bash version you have is v3 and doesn't support `${var^^}` syntax

looks like I have v3, yeah

> can you run echo 'hello' | tr 'a-z' 'A-Z' is a shell and see if that uppercases it for you

That seems to be working

```
$ echo 'hello' | tr 'a-z' 'A-Z'
HELLO
```

**Comment by paulbarton90** [comment]
So I have got this working in bash 3 (via a docker container running bash 3), and my system. You should be able to upgrade to it via `gh extensions upgrade paulbarton90/gh-clean-notifications` or `gh extensions install --force  paulbarton90/gh-clean-notifications`.


```
user@389e59cba888:~/.local/share/gh/extensions/gh-clean-notifications# gh clean-notifications
gh: Field 'notificationThreads' doesn't exist on type 'User'
Variable $first is declared by NotificationsQuery but not used
Variable $endCursor is declared by NotificationsQuery but not used
Variable $miscQuery is declared by NotificationsQuery but not used
```

For the above error, you'll need to authenticate for gh via `gh auth login --scopes notification` and use the `Login with a web browser` workflow. For some reason this token provides a working token. I don't know why going via `Paste an authentication token` does not.

**Comment by gr2m** [comment]
Thank you, that worked! Confirmed that it fails if I paste a token or if I have `GITHUB_TOKEN` defined as environment variable 🤷
